name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Set up Docker Buildx (needed for caching / cross-platform)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to DockerHub (only if you want to push the image)
      # Add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN in GitHub > Settings > Secrets
      - name: Log in to DockerHub
