name: Docker Build CI (No Secrets)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install openpyxl pytest

      - name: Run Quick Tests Only
        run: |
          pytest -m "quick" -v

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
